version: '2'

services:
  goms:
    image: goms/goms
    ports:
      - 8085:8080
    restart: always
    command:
    - -db_type=mysql
    - -db_connection_string=devsuser:devspassword@tcp(gomsmysqldb:3306)/devsupport
    links:
      - gomsmysqldb:gomsmysqldb
    depends_on:
        - "gomsmysqldb"
  gomsmysqldb:
    image: mysql
    container_name: mysql
    restart: always
    environment:
        - MYSQL_DATABASE=devsupport
        - MYSQL_ROOT_PASSWORD=devrootsupport
        - MYSQL_USER=devsuser
        - MYSQL_PASSWORD=devspassword
    volumes:
        - /home/artpar/devs-mysql:/var/lib/mysql
